[package]
name = "day21"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bucket_queue = "2.0.0"
hibitset = "0.6.4"
rustc-hash = "1.1.0"

[dev-dependencies]
criterion = "0.5.1"
